name: Energy Build and Package Linux Test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Linux-arm64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-20.04 ]
        include:
          - arch: arm64v8
            distro: ubuntu:18.04

    steps:
      - uses: actions/checkout@v4

      - name: Config Base Environment
        run: |
          mkdir $RUNNER_WORKSPACE/install
          mv ./.github/shell $RUNNER_WORKSPACE/shell
          chmod -R +x $RUNNER_WORKSPACE/shell

      - name: Container Build and Package
        uses: uraimo/run-on-arch-action@v2
        id: build
        with:
          arch: none
          distro: none
          base_image: ${{ matrix.arch }}/${{ matrix.distro }}

          githubToken: ${{ github.token }}

          dockerRunArgs: |
            --volume "$RUNNER_WORKSPACE:/app"

          env: |
            GoVer: go1.20.14.linux-arm64.tar.gz

          shell: /bin/bash

          install: |
            apt-get update -q -y
            apt-get install -q -y git wget p7zip-full
            apt-get install -q -y make binutils build-essential gdb subversion zip unzip libx11-dev libgtk2.0-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev libgtk-3-dev

          run: |
            export GOBIN=/app/go/bin
            export PATH=$PATH:/app/go/bin

            /app/shell/install-go.sh $GoVer

            /app/shell/install-energy.sh

            energy install --all
            energy env

            cd /app/demo-actions
            go env -w GOFLAGS=-buildvcs=false
            energy build -o demo
            energy package -f demo -o demo-apparm64.deb
            file demo
            
            mv /app/demo-actions/build/linux/demo-apparm64.deb  /app/install

      - name: Build and Package END
        run: |
          ls -l $RUNNER_WORKSPACE/install

      - name: Release Dynamic library
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ../install/**

