name: Energy Build and Package MacOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  macos-amd64-arm64:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ macos-13 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Config Base Environment
        run: |
          mkdir $RUNNER_WORKSPACE/app
          mkdir $RUNNER_WORKSPACE/app/install

      - name: Install ENERGY CLI
        run: |
          cd $RUNNER_WORKSPACE/app
          git clone https://github.com/energye/energy.git
          cd energy/cmd/energy
          go install

      - name: Install ENERGY ENV
        run: |
          cd $RUNNER_WORKSPACE/app

      - name: Release Dynamic library # 版本发布上传liblcl二进制
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "../app/install/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}